# -*- coding: utf-8 -*-
"""EDA_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EbAiHWtLpg6xgZgVWO_KC8nKfcJvzuFU
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_excel('WA_Fn-UseC_-HR-Employee-Attrition.xlsx')
df.head(5)

df.describe()

df = df.drop(['Over18', 'StandardHours'], axis=1)

"""Убираем столбцы over18 и StandardHours"""

cols = df.columns
for ind in cols:
  plt.figure(figsize=(15,15),dpi=80)
  sns.set_style('whitegrid')
  sns.countplot(x=ind,data=df,palette='colorblind')
  plt.xticks(rotation=45)
  plt.xlabel(ind)
  plt.show()

"""Гистограммы по каждому столбцу"""

attrited_df = df[df['Attrition'] == 'Yes']
attrited_df

"""Таблица только с уволившимися"""

sns.set_style('whitegrid')
sns.countplot(x='Gender',data=attrited_df,palette='colorblind')

plt.show()

большинство уволившихся мужчины

sns.set_style('whitegrid')
sns.countplot(x='Education',data=attrited_df,palette='colorblind')

plt.show()

"""Большинство уволившихся имели высокий уровень образования"""

sns.set_style('whitegrid')
sns.countplot(x='Department',data=attrited_df,palette='colorblind')

plt.show()

"""Большинство людей уходило из research & Development Department"""

sns.set_style('darkgrid')
plt.figure(figsize=(10,10),dpi=80)
sns.countplot(x='Age',data=attrited_df,palette='colorblind')

plt.xlabel('Age')
plt.show()

"""Больше всего людей уходило в возрасте от 26 до 35(достаточно молодые специалисты)"""

sns.set_style('darkgrid')
plt.figure(figsize=(10,10),dpi=80)
sns.countplot(x='JobRole',data=attrited_df,palette='colorblind')

plt.xlabel('JobRole')
plt.xticks(rotation=45)
plt.show()

"""Большинство уволившихся были или техническими лаборантами,или директорами по продажам, или научными исследователями"""

sns.set_style('darkgrid')
plt.figure(figsize=(10,10),dpi=80)
sns.countplot(x='DistanceFromHome',data=attrited_df,palette='colorblind')



plt.show()

"""Большая часть уволившихся жила рядом с работой"""

sns.set_style('whitegrid')
sns.countplot(x='MaritalStatus',data=attrited_df,palette='colorblind')

plt.show()

"""большая часть увольвшихся была не жената/не замужем"""

sns.set_style('whitegrid')
sns.countplot(x='RelationshipSatisfaction',data=attrited_df,palette='colorblind')

plt.show()

"""Много людей не было удовлетворены коллективом"""

sns.set_style('whitegrid')
sns.countplot(x='EnvironmentSatisfaction',data=attrited_df,palette='colorblind')

plt.show()

"""Большинству не нравилась обстановка на работе"""

sns.set_style('whitegrid')
sns.countplot(x='WorkLifeBalance',data=attrited_df,palette='colorblind')

plt.show()

"""Большинство имело хороший баланс между личной жизнью и работой"""

sns.set_style('darkgrid')
plt.figure(figsize=(10,10),dpi=80)
sns.countplot(x='YearsAtCompany',data=attrited_df,palette='colorblind')

plt.show()

"""Большинство не проводило и двух лет в компании """

sns.set_style('darkgrid')
plt.figure(figsize=(10,10),dpi=80)
sns.countplot(x='YearsWithCurrManager',data=attrited_df,palette='colorblind')

plt.show()

"""Большинство и года не пробыло с текущим менеджером"""

sns.set_style('whitegrid')
sns.countplot(x='PerformanceRating',data=attrited_df,palette='colorblind')

plt.show()

"""Все уволившиеся отлично справлялись с работой

"""

for line in df['MonthlyIncome']:
  
  if line >= 2000 and line < 3000:
    attrited_df.loc[(df.MonthlyIncome == line), 'MonthlyIncome' ] = 2500
  elif line >= 3000 and line < 4000:
    attrited_df.loc[(df.MonthlyIncome == line), 'MonthlyIncome' ] = 3500
  elif line >= 4000 and line < 5000:
    attrited_df.loc[(df.MonthlyIncome == line), 'MonthlyIncome' ] = 4500
  elif line >= 5000 and line < 6000:
    attrited_df.loc[(df.MonthlyIncome == line), 'MonthlyIncome' ] = 5500
  elif line >= 6000 and line < 7000:
    attrited_df.loc[(df.MonthlyIncome == line), 'MonthlyIncome' ] = 6500
  elif line >= 7000 and line < 8000:
    attrited_df.loc[(df.MonthlyIncome == line), 'MonthlyIncome' ] = 7500
  elif line >= 8000 and line < 9000:
    attrited_df.loc[(df.MonthlyIncome == line), 'MonthlyIncome' ] = 8500
  elif line >= 9000 and line < 10000:
    attrited_df.loc[(df.MonthlyIncome == line), 'MonthlyIncome' ] = 9500
  elif line >= 10000:
    attrited_df.loc[(df.MonthlyIncome == line), 'MonthlyIncome' ] = 10000


sns.set_style('darkgrid')
plt.figure(figsize=(10,10),dpi=80)
sns.countplot(x='MonthlyIncome',data=attrited_df,palette='colorblind')
plt.xticks(rotation=45)
plt.show()

"""большая часть зарабатывала от 2000 до 3000

ВЫВОД:

Большинство уволившихся в возрасте от 26 до 35 не проработали больше двух лет в компании, а с текущим менеджером и года. У большинства также наблюдается неприязнь к окружающей рабочей обстановке, а также проблема с взаимоотношениями в коллективе. Также многие уволившиеся были или техническими лаборантами или научными исследователями, т.е. были в одном департаменте исследований и разработки и получали достаточно низкую зарплату от 2000 до 3000. У подавляющего числа уволившихся дистанция от дома до работы маленькая, баланс между жизнью и работой хороший
"""